version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: regula_neo4j
    environment:
      - NEO4J_AUTH=neo4j/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
volumes:
  neo4j_data:
  neo4j_logs:

